import Approach from '@/components/Approach'
import Gallery from '@/components/Gallery'
import Hero from '@/components/Hero'
import Intro from '@/components/Intro'
import Quote from '@/components/Quote'
import ServicesMain from '@/components/ServicesMain'
import Testimonials from '@/components/Testimonials'
import Head from 'next/head'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <ServicesMain />
        <Intro />
        <Approach />
        <Gallery />
        <Testimonials />
        <Quote />
      </main>
    </>
  )
}
